"""
Phase 2.3 — Suite Hygiene

Weekly scan to keep test suites clean:
- Stale cases (not run in 90 days)
- Flaky cases (< 80% pass rate)
- Duplicate coverage (> 85% title similarity)
- Orphaned refs (closed RCA, no recent activity)
- Pipeline-generated, never verified
- Coverage gaps from RCA history
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta
from enum import Enum
from dataclasses import dataclass, field
from difflib import SequenceMatcher
import sqlite3
from pathlib import Path

from mcp.tools.testrail_tool import get_all_cases, get_results_for_case, _tr
from mcp.db.rca_store import get_recent_rcas, get_rcas_by_stage
from mcp.models.rca_models import PipelineStage
from mcp.utils.logger import get_logger
from config import settings

logger = get_logger(__name__)

# SQLite store for hygiene reports
HYGIENE_DB_PATH = Path(__file__).parent.parent.parent.parent / "data" / "suite_hygiene.db"


class HygieneIssueType(str, Enum):
    """Types of hygiene issues."""
    STALE = "stale"
    FLAKY = "flaky"
    DUPLICATE = "duplicate"
    ORPHANED_REFS = "orphaned_refs"
    UNVERIFIED_GENERATED = "unverified_generated"
    COVERAGE_GAP = "coverage_gap"


@dataclass
class HygieneIssue:
    """A single hygiene issue found in the suite."""
    issue_type: HygieneIssueType
    case_id: int
    title: str
    severity: str  # high, medium, low
    details: str
    recommended_action: str
    related_case_id: Optional[int] = None  # For duplicates


@dataclass
class HygieneReport:
    """Complete hygiene report for a suite."""
    report_id: str
    generated_at: datetime
    suite_id: int
    total_cases: int
    issues: List[HygieneIssue] = field(default_factory=list)
    summary: Dict[str, int] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "report_id": self.report_id,
            "generated_at": self.generated_at.isoformat(),
            "suite_id": self.suite_id,
            "total_cases": self.total_cases,
            "issues": [
                {
                    "issue_type": i.issue_type.value,
                    "case_id": i.case_id,
                    "title": i.title,
                    "severity": i.severity,
                    "details": i.details,
                    "recommended_action": i.recommended_action,
                    "related_case_id": i.related_case_id
                }
                for i in self.issues
            ],
            "summary": self.summary,
            "total_issues": len(self.issues)
        }


class SuiteHygieneChecker:
    """
    Runs hygiene checks on TestRail suites.
    
    Checks:
    1. Stale: Not in any run for 90 days
    2. Flaky: < 80% pass rate over 10 runs
    3. Duplicate: > 85% title similarity in same section
    4. Orphaned: refs to closed RCA, no activity in 90 days
    5. Unverified: Generated by pipeline, never passed
    6. Coverage gap: Service in 3+ RCAs with < 5 test cases
    """
    
    def __init__(self):
        self.stale_days = 90
        self.flaky_threshold = 0.8
        self.similarity_threshold = 0.85
        self.min_rca_for_gap = 3
        self.min_cases_for_coverage = 5
        self._init_db()
    
    def _init_db(self):
        """Initialize hygiene report database."""
        HYGIENE_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(HYGIENE_DB_PATH))
        conn.execute("""
            CREATE TABLE IF NOT EXISTS hygiene_reports (
                report_id TEXT PRIMARY KEY,
                suite_id INTEGER,
                generated_at TEXT,
                data JSON
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS hygiene_actions (
                action_id TEXT PRIMARY KEY,
                report_id TEXT,
                case_id INTEGER,
                action_type TEXT,
                approved_by TEXT,
                approved_at TEXT,
                executed_at TEXT
            )
        """)
        conn.commit()
        conn.close()
    
    def run_check(self, suite_id: Optional[int] = None) -> HygieneReport:
        """
        Run full hygiene check on a suite.
        
        Args:
            suite_id: TestRail suite ID (defaults to configured default)
            
        Returns:
            HygieneReport with all issues found
        """
        suite_id = suite_id or settings.testrail_default_suite_id
        
        logger.info("suite_hygiene_check_started", suite_id=suite_id)
        
        report = HygieneReport(
            report_id=f"hygiene-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}",
            generated_at=datetime.utcnow(),
            suite_id=suite_id,
            total_cases=0,
            summary={t.value: 0 for t in HygieneIssueType}
        )
        
        # Get all cases in suite
        cases = get_all_cases(suite_id)
        report.total_cases = len(cases)
        
        # Get RCA history
        rca_history = self._build_rca_history()
        
        # Run all checks
        report.issues.extend(self._check_stale(cases))
        report.issues.extend(self._check_flaky(cases))
        report.issues.extend(self._check_duplicates(cases))
        report.issues.extend(self._check_orphaned_refs(cases, rca_history))
        report.issues.extend(self._check_unverified_generated(cases))
        report.issues.extend(self._check_coverage_gaps(cases, rca_history))
        
        # Update summary
        for issue in report.issues:
            report.summary[issue.issue_type.value] += 1
        
        # Store report
        self._store_report(report)
        
        logger.info(
            "suite_hygiene_check_complete",
            suite_id=suite_id,
            total_issues=len(report.issues),
            summary=report.summary
        )
        
        return report
    
    def _check_stale(self, cases: List[Dict]) -> List[HygieneIssue]:
        """Find cases not included in any run for 90 days."""
        issues = []
        cutoff = datetime.utcnow() - timedelta(days=self.stale_days)
        
        for case in cases:
            try:
                results = get_results_for_case(case["id"], limit=1)
                if not results:
                    issues.append(HygieneIssue(
                        issue_type=HygieneIssueType.STALE,
                        case_id=case["id"],
                        title=case.get("title", ""),
                        severity="medium",
                        details=f"No test results found (never run)",
                        recommended_action="Review for relevance or add to active suite"
                    ))
                else:
                    last_run = results[0].get("created_on")
                    if last_run:
                        last_date = datetime.fromtimestamp(last_run)
                        if last_date < cutoff:
                            days_stale = (datetime.utcnow() - last_date).days
                            issues.append(HygieneIssue(
                                issue_type=HygieneIssueType.STALE,
                                case_id=case["id"],
                                title=case.get("title", ""),
                                severity="low",
                                details=f"Not run in {days_stale} days",
                                recommended_action="Include in upcoming run or retire"
                            ))
            except Exception:
                continue
        
        return issues
    
    def _check_flaky(self, cases: List[Dict]) -> List[HygieneIssue]:
        """Find cases with < 80% pass rate."""
        issues = []
        
        for case in cases:
            try:
                results = get_results_for_case(case["id"], limit=10)
                if len(results) >= 5:  # Need enough data
                    passed = sum(1 for r in results if r.get("status_id") == 1)
                    pass_rate = passed / len(results)
                    
                    if pass_rate < self.flaky_threshold:
                        issues.append(HygieneIssue(
                            issue_type=HygieneIssueType.FLAKY,
                            case_id=case["id"],
                            title=case.get("title", ""),
                            severity="high" if pass_rate < 0.5 else "medium",
                            details=f"Pass rate: {pass_rate:.0%} over {len(results)} runs",
                            recommended_action="Quarantine to flaky suite for investigation"
                        ))
            except Exception:
                continue
        
        return issues
    
    def _check_duplicates(self, cases: List[Dict]) -> List[HygieneIssue]:
        """Find cases with > 85% title similarity in same section."""
        issues = []
        seen_pairs = set()
        
        # Group by section
        by_section: Dict[int, List[Dict]] = {}
        for case in cases:
            section_id = case.get("section_id", 0)
            if section_id not in by_section:
                by_section[section_id] = []
            by_section[section_id].append(case)
        
        for section_id, section_cases in by_section.items():
            for i, case1 in enumerate(section_cases):
                for case2 in section_cases[i+1:]:
                    pair = tuple(sorted([case1["id"], case2["id"]]))
                    if pair in seen_pairs:
                        continue
                    
                    similarity = SequenceMatcher(
                        None,
                        case1.get("title", "").lower(),
                        case2.get("title", "").lower()
                    ).ratio()
                    
                    if similarity > self.similarity_threshold:
                        seen_pairs.add(pair)
                        issues.append(HygieneIssue(
                            issue_type=HygieneIssueType.DUPLICATE,
                            case_id=case1["id"],
                            title=case1.get("title", ""),
                            severity="medium",
                            details=f"{similarity:.0%} similar to case {case2['id']}",
                            recommended_action="Merge or retire duplicate",
                            related_case_id=case2["id"]
                        ))
        
        return issues
    
    def _check_orphaned_refs(
        self,
        cases: List[Dict],
        rca_history: Dict[str, Any]
    ) -> List[HygieneIssue]:
        """Find cases with refs to closed RCA tickets."""
        issues = []
        
        for case in cases:
            refs = case.get("refs") or ""
            if refs and refs in rca_history:
                rca = rca_history[refs]
                if rca.get("stage") == "completed":
                    days_since = rca.get("days_since_close", 0)
                    if days_since > 90:
                        issues.append(HygieneIssue(
                            issue_type=HygieneIssueType.ORPHANED_REFS,
                            case_id=case["id"],
                            title=case.get("title", ""),
                            severity="low",
                            details=f"refs {refs} closed {days_since} days ago",
                            recommended_action="Candidate for retirement"
                        ))
        
        return issues
    
    def _check_unverified_generated(self, cases: List[Dict]) -> List[HygieneIssue]:
        """Find pipeline-generated cases that never passed."""
        issues = []
        
        for case in cases:
            # Check if case was generated by pipeline (custom_automation_type = 2)
            auto_type = case.get("custom_automation_type", 0)
            if auto_type == 2:
                try:
                    results = get_results_for_case(case["id"], limit=10)
                    passed_any = any(r.get("status_id") == 1 for r in results)
                    
                    if not passed_any:
                        issues.append(HygieneIssue(
                            issue_type=HygieneIssueType.UNVERIFIED_GENERATED,
                            case_id=case["id"],
                            title=case.get("title", ""),
                            severity="high",
                            details="Generated by pipeline but never passed",
                            recommended_action="Investigate why test never passed"
                        ))
                except Exception:
                    continue
        
        return issues
    
    def _check_coverage_gaps(
        self,
        cases: List[Dict],
        rca_history: Dict[str, Any]
    ) -> List[HygieneIssue]:
        """Find services with 3+ RCAs but < 5 test cases."""
        issues = []
        
        # Count cases per service/refs
        cases_per_service: Dict[str, int] = {}
        for case in cases:
            refs = case.get("refs") or ""
            if refs:
                cases_per_service[refs] = cases_per_service.get(refs, 0) + 1
        
        # Find services with high RCA count but low test coverage
        for service, rca_data in rca_history.items():
            rca_count = rca_data.get("count", 0)
            test_count = cases_per_service.get(service, 0)
            
            if rca_count >= self.min_rca_for_gap and test_count < self.min_cases_for_coverage:
                issues.append(HygieneIssue(
                    issue_type=HygieneIssueType.COVERAGE_GAP,
                    case_id=0,  # No specific case
                    title=f"Coverage gap: {service}",
                    severity="high",
                    details=f"{rca_count} RCAs but only {test_count} test cases",
                    recommended_action="Generate additional test cases for this service"
                ))
        
        return issues
    
    def _build_rca_history(self) -> Dict[str, Any]:
        """Build RCA history map for checks."""
        history = {}
        try:
            recent = get_recent_rcas(limit=200)
            for rca in recent:
                key = rca.jira_ticket_id or rca.service_name
                if key:
                    if key not in history:
                        history[key] = {"count": 0, "stage": None, "days_since_close": 0}
                    history[key]["count"] += 1
                    history[key]["stage"] = rca.stage.value
                    if rca.closed_at:
                        days = (datetime.utcnow() - rca.closed_at).days
                        history[key]["days_since_close"] = days
        except Exception:
            pass
        return history
    
    def _store_report(self, report: HygieneReport):
        """Store report in SQLite."""
        import json
        conn = sqlite3.connect(str(HYGIENE_DB_PATH))
        conn.execute(
            "INSERT OR REPLACE INTO hygiene_reports VALUES (?, ?, ?, ?)",
            (report.report_id, report.suite_id, report.generated_at.isoformat(),
             json.dumps(report.to_dict()))
        )
        conn.commit()
        conn.close()
    
    def get_report(self, report_id: str) -> Optional[Dict[str, Any]]:
        """Retrieve a stored report."""
        import json
        conn = sqlite3.connect(str(HYGIENE_DB_PATH))
        row = conn.execute(
            "SELECT data FROM hygiene_reports WHERE report_id = ?",
            (report_id,)
        ).fetchone()
        conn.close()
        
        if row:
            return json.loads(row[0])
        return None
    
    def get_latest_report(self, suite_id: Optional[int] = None) -> Optional[Dict[str, Any]]:
        """Get the most recent report for a suite."""
        import json
        suite_id = suite_id or settings.testrail_default_suite_id
        
        conn = sqlite3.connect(str(HYGIENE_DB_PATH))
        row = conn.execute(
            "SELECT data FROM hygiene_reports WHERE suite_id = ? ORDER BY generated_at DESC LIMIT 1",
            (suite_id,)
        ).fetchone()
        conn.close()
        
        if row:
            return json.loads(row[0])
        return None
    
    def apply_actions(
        self,
        report_id: str,
        approved_actions: List[Dict[str, Any]],
        approver_id: str
    ) -> Dict[str, Any]:
        """Apply approved hygiene actions."""
        results = {
            "applied": [],
            "failed": [],
            "skipped": []
        }
        
        for action in approved_actions:
            case_id = action.get("case_id")
            action_type = action.get("action_type")
            
            try:
                if action_type == "retire":
                    # Would call TestRail API to delete/archive case
                    results["applied"].append({
                        "case_id": case_id,
                        "action": "retired"
                    })
                elif action_type == "quarantine":
                    # Would move to quarantine suite
                    results["applied"].append({
                        "case_id": case_id,
                        "action": "quarantined"
                    })
                else:
                    results["skipped"].append({
                        "case_id": case_id,
                        "reason": f"Unknown action: {action_type}"
                    })
            except Exception as e:
                results["failed"].append({
                    "case_id": case_id,
                    "error": str(e)
                })
        
        return results


# Singleton instance
suite_hygiene_checker = SuiteHygieneChecker()


def run_hygiene_check(suite_id: Optional[int] = None) -> Dict[str, Any]:
    """Convenience function for hygiene check."""
    report = suite_hygiene_checker.run_check(suite_id)
    return report.to_dict()


def get_hygiene_report(report_id: str = None, suite_id: int = None) -> Optional[Dict[str, Any]]:
    """Get a hygiene report."""
    if report_id:
        return suite_hygiene_checker.get_report(report_id)
    return suite_hygiene_checker.get_latest_report(suite_id)
